News week milestone3
fortuneonyeka/bootstrap-newsweek pull request #4
Opened 2021-04-14 19:36 UTC by fortuneonyeka

Milestone3 with bootstrap

2021-04-14 21:01 UTC, christianotieno requested changes
## Changes required ♻️ 
Hello @fortuneonyeka & @marcosmerida  👋🏾 

Congratulations on the hard work done in the third, milestone of this project.
Kindly note that for this final milestone, we need to ensure nothing is made up. Let's take care of the small suggested change below before we proceed.

## mandatory
- [ ] Take note of the spacings required on the `navbar`, `footer` and the first section of the page.

### Happy coding 💻 
#### Christian Otieno (CR)

2021-04-14 21:01 UTC, christianotieno commented on index.html
> +                <div class="row">
### Spacing
- [ ] Let's be mindful of the spacings on the rest of the contest. They all should be having a uniform margin as the page need not be covering the whole view width of the screen bootstrap `contani3er` class can help us achieve this, do you mind implementing thin?

|Source Page|Clone Page|
|:--:|:--:|
|![source](https://user-images.githubusercontent.com/22345961/114778489-961eb600-9d7d-11eb-8e45-30386c41c3d0.png)|![clone](https://user-images.githubusercontent.com/22345961/114778507-9dde5a80-9d7d-11eb-8aec-235333d219cd.png)|

2021-04-15 00:18 UTC, george-shammar approved these changes
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

**You've done a great job**. :ok_hand: :ok_hand: 

**Congratulations.** :+1: :+1: 

[OPTIONAL]

- [ ] **Further reduce the margin on both sides of the page. The margin is still wider than the original page. With that, your project would be almost flawless.**

**You may go ahead and merge this branch.**

**I wish you good luck with your future projects.**

2021-04-15 14:29 UTC, fortuneonyeka commented
> ### **STATUS: APPROVED** ✔️ ✔️
> **You've done a great job**. 👌 👌
> 
> **Congratulations.** 👍 👍
> 
> [OPTIONAL]
> 
> * [ ]  **Further reduce the margin on both sides of the page. The margin is still wider than the original page. With that, your project would be almost flawless.**
> 
> **You may go ahead and merge this branch.**
> 
> **I wish you good luck with your future projects.**

Thank you very much, George

2021-04-15 14:30 UTC, merged